# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Katzy  
tagline:          ...a yellow brick blog.
url:              http://katzy.github.io
paginate:         1
baseurl:          /
author:
  name:           Scott Katz
  url:            
  email:          scottalankatz@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
